### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/wye-blog#1]
- [x] Theme, logos, layout
- [x] Readme, setup, deployment, travis
- [ ] Subscribe, comments(disqus?)
- [x] Link to PE social sites
- [x] Posts archives/pagination

@vnbang2003 @kracekumar Please add anything that needs to be done.

**Comment by kracekumar** [comment]
One missing feature, deploy to GHPages for PR merge. @ChillarAnand

**Comment by ChillarAnand** [comment]
It should [auto deploy](https://github.com/pythonindia/wye-blog/blob/master/.travis.yml#L11). Added instructions to [deploy manually](https://github.com/pythonindia/wye-blog/commit/1658efe107409fbecc6d9ada8699e9c070bf40a1).
